# Install
in:
	java -jar /usr/local/lib/antlr-4.7.1-complete.jar PointTag.g4
	javac *.java

# view
vi:
	java -Dfile.encoding=UTF-8 org.antlr.v4.gui.TestRig PointTag prog  -gui t.txt

vi2:
	java -Dfile.encoding=UTF-8 org.antlr.v4.gui.TestRig PointTag prog  -gui b.txt


# Clean up
cl:
	rm -f  *.o  *.interp *.tokens
	rm -f  *.java *.class
	rm -f  *.js
	rm -f  *.cs
