//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from PointTag.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IPointTagListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public partial class PointTagBaseListener : IPointTagListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="PointTagParser.prog"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProg([NotNull] PointTagParser.ProgContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PointTagParser.prog"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProg([NotNull] PointTagParser.ProgContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PointTagParser.statements"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatements([NotNull] PointTagParser.StatementsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PointTagParser.statements"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatements([NotNull] PointTagParser.StatementsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>IfStatement</c>
	/// labeled alternative in <see cref="PointTagParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfStatement([NotNull] PointTagParser.IfStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>IfStatement</c>
	/// labeled alternative in <see cref="PointTagParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfStatement([NotNull] PointTagParser.IfStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Value_stat</c>
	/// labeled alternative in <see cref="PointTagParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValue_stat([NotNull] PointTagParser.Value_statContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Value_stat</c>
	/// labeled alternative in <see cref="PointTagParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValue_stat([NotNull] PointTagParser.Value_statContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>PreAdd</c>
	/// labeled alternative in <see cref="PointTagParser.ifStat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPreAdd([NotNull] PointTagParser.PreAddContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>PreAdd</c>
	/// labeled alternative in <see cref="PointTagParser.ifStat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPreAdd([NotNull] PointTagParser.PreAddContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>PostAdd</c>
	/// labeled alternative in <see cref="PointTagParser.ifStat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPostAdd([NotNull] PointTagParser.PostAddContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>PostAdd</c>
	/// labeled alternative in <see cref="PointTagParser.ifStat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPostAdd([NotNull] PointTagParser.PostAddContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Replace</c>
	/// labeled alternative in <see cref="PointTagParser.ifStat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReplace([NotNull] PointTagParser.ReplaceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Replace</c>
	/// labeled alternative in <see cref="PointTagParser.ifStat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReplace([NotNull] PointTagParser.ReplaceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>If</c>
	/// labeled alternative in <see cref="PointTagParser.ifStat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIf([NotNull] PointTagParser.IfContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>If</c>
	/// labeled alternative in <see cref="PointTagParser.ifStat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIf([NotNull] PointTagParser.IfContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Cond</c>
	/// labeled alternative in <see cref="PointTagParser.condition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCond([NotNull] PointTagParser.CondContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Cond</c>
	/// labeled alternative in <see cref="PointTagParser.condition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCond([NotNull] PointTagParser.CondContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PointTagParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValue([NotNull] PointTagParser.ValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PointTagParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValue([NotNull] PointTagParser.ValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PointTagParser.other_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOther_value([NotNull] PointTagParser.Other_valueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PointTagParser.other_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOther_value([NotNull] PointTagParser.Other_valueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PointTagParser.other"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOther([NotNull] PointTagParser.OtherContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PointTagParser.other"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOther([NotNull] PointTagParser.OtherContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
