//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from PointTag.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="PointTagParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public interface IPointTagListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="PointTagParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProg([NotNull] PointTagParser.ProgContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PointTagParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProg([NotNull] PointTagParser.ProgContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PointTagParser.statements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatements([NotNull] PointTagParser.StatementsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PointTagParser.statements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatements([NotNull] PointTagParser.StatementsContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>IfStatement</c>
	/// labeled alternative in <see cref="PointTagParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfStatement([NotNull] PointTagParser.IfStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>IfStatement</c>
	/// labeled alternative in <see cref="PointTagParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfStatement([NotNull] PointTagParser.IfStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Value_stat</c>
	/// labeled alternative in <see cref="PointTagParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValue_stat([NotNull] PointTagParser.Value_statContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Value_stat</c>
	/// labeled alternative in <see cref="PointTagParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValue_stat([NotNull] PointTagParser.Value_statContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>PreAdd</c>
	/// labeled alternative in <see cref="PointTagParser.ifStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPreAdd([NotNull] PointTagParser.PreAddContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>PreAdd</c>
	/// labeled alternative in <see cref="PointTagParser.ifStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPreAdd([NotNull] PointTagParser.PreAddContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>PostAdd</c>
	/// labeled alternative in <see cref="PointTagParser.ifStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPostAdd([NotNull] PointTagParser.PostAddContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>PostAdd</c>
	/// labeled alternative in <see cref="PointTagParser.ifStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPostAdd([NotNull] PointTagParser.PostAddContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Replace</c>
	/// labeled alternative in <see cref="PointTagParser.ifStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReplace([NotNull] PointTagParser.ReplaceContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Replace</c>
	/// labeled alternative in <see cref="PointTagParser.ifStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReplace([NotNull] PointTagParser.ReplaceContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>If</c>
	/// labeled alternative in <see cref="PointTagParser.ifStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIf([NotNull] PointTagParser.IfContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>If</c>
	/// labeled alternative in <see cref="PointTagParser.ifStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIf([NotNull] PointTagParser.IfContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Cond</c>
	/// labeled alternative in <see cref="PointTagParser.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCond([NotNull] PointTagParser.CondContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Cond</c>
	/// labeled alternative in <see cref="PointTagParser.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCond([NotNull] PointTagParser.CondContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PointTagParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValue([NotNull] PointTagParser.ValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PointTagParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValue([NotNull] PointTagParser.ValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PointTagParser.other_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOther_value([NotNull] PointTagParser.Other_valueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PointTagParser.other_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOther_value([NotNull] PointTagParser.Other_valueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PointTagParser.other"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOther([NotNull] PointTagParser.OtherContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PointTagParser.other"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOther([NotNull] PointTagParser.OtherContext context);
}
