# Install
in1:
	java -jar /usr/local/lib/antlr-4.7.1-complete.jar GE.g4
	javac *.java

# view
vi1:
	java -Dfile.encoding=UTF-8 org.antlr.v4.gui.TestRig GE file -gui ff.tree


in2:
	java -jar /usr/local/lib/antlr-4.7.1-complete.jar GE_Expr.g4
	javac *.java

# view
vi2:
	java -Dfile.encoding=UTF-8 org.antlr.v4.gui.TestRig GE_Expr prog -gui  Ftest.tree



# Clean up
cl:
	rm -f  *.o  *.interp *.tokens
	rm -f  *.java *.class
	rm -f  *.js
	rm -f  *.cs
