# Install
in:
	java -jar /usr/local/lib/antlr-4.7.1-complete.jar JSON.g4
	javac *.java

# view
vi:
	java org.antlr.v4.gui.TestRig GE file -gui 

# Clean up
cl:
	rm -f  *.o  *.interp *.tokens
	rm -f  *.java *.class
	rm -f  *.js
	rm -f  *.cs
