//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Transform.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="TransformParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public interface ITransformListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="TransformParser.transform"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTransform([NotNull] TransformParser.TransformContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TransformParser.transform"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTransform([NotNull] TransformParser.TransformContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TransformParser.sentence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSentence([NotNull] TransformParser.SentenceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TransformParser.sentence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSentence([NotNull] TransformParser.SentenceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TransformParser.funcname"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncname([NotNull] TransformParser.FuncnameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TransformParser.funcname"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncname([NotNull] TransformParser.FuncnameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TransformParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValue([NotNull] TransformParser.ValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TransformParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValue([NotNull] TransformParser.ValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TransformParser.valueList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValueList([NotNull] TransformParser.ValueListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TransformParser.valueList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValueList([NotNull] TransformParser.ValueListContext context);
}
